name: goffi
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  # ffigen: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # golang 绑定
  # bindgo: ^0.2.0
  # 查找so文件
  # dylib: ^0.3.2+1

flutter:

  uses-material-design: true

# ffigen:
#   output: 'lib/ffi/arm64-v8a/libgo.h.dart'
#   headers:
#     entry-points:
#       - 'lib/ffi/arm64-v8a/libgo.h'

# ffigen:
#   output: 'lib/ffi/armeabi-v7a/libgo.h.dart'
#   headers:
#     entry-points:
#       - 'lib/ffi/armeabi-v7a/libgo.h'

# ffigen:
#   output: 'lib/ffi/x86/libgo.h.dart'
#   headers:
#     entry-points:
#       - 'lib/ffi/x86/libgo.h'

# ffigen:
#   output: 'lib/ffi/x86_64/libgo.h.dart'
#   headers:
#     entry-points:
#       - 'lib/ffi/x86_64/libgo.h'
# bindgo:
#   name: gets
#   main: ./golib
#   platforms:
#     linux:
#       arch:
#         - 'amd64'
#     android:
#       arch:
#         - 'arm64'
#         - 'amd64'
#       # cc: '/home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang'
#       cc: '/home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android30-clang'
